### ISSUE TITLE
Python 3.12 - AttributeError: module 'pathlib' has no attribute '_Flavour'

### ISSUE THREAD

**Issue by briantist** [devopshq/artifactory#430]
Python 3.12 is now released, but it does not work due to pathlib changes:

> /opt/hostedtoolcache/Python/3.12.0-rc.1/x64/lib/python3.12/site-packages/artifactory.py:426: in <module>
>     class _ArtifactoryFlavour(pathlib._Flavour):
> E   AttributeError: module 'pathlib' has no attribute '_Flavour'

I figured I'd add 3.12 into the test matrix on my project which relies on this library, and that's how I found this issue:
- https://github.com/briantist/galactory/actions/runs/5844080610/job/15846784439?pr=80#step:5:40

Not any kind of pressing issue yet.

**Comment by allburov** [comment]
Thank you for the feedback!
If anyone has idea how to fix this - feel free to create a PR

**Comment by brot** [comment]
Python 3.12 will [add support for subclassing pathlib.PurePath and Path](https://docs.python.org/3.12/whatsnew/3.12.html#pathlib)

See also the cpython github issue: https://github.com/python/cpython/pull/31691

**Comment by barneygale** [comment]
I'm hoping to add a `pathlib.PathBase` class for Python 3.13. Once it's in the codebase, I'll publish a backport package on PyPI for Python <3.13. `dohq-artifactory` could subclass `PathBase` to implement `ArtifactoryPath`.

CPython issue: https://github.com/python/cpython/issues/110109

**Comment by barneygale** [comment]
I'd recommend that you wait if you can - I'm expecting to publish a PyPI package with the base classes some time this month.

**Comment by barneygale** [comment]
Preview: https://github.com/python/cpython/blob/33f9af159adce62008934a6d304511401d650a8d/Lib/pathlib/_abc.py#L535

**Comment by barneygale** [comment]
Git project: https://github.com/barneygale/pathlib_abc

Currently it only supports Python 3.11+, but I should have it working for 3.8+ within a couple of weeks, at which point I'll publish a PyPI package.

**Comment by barneygale** [comment]
First PyPI release: https://pypi.org/project/pathlib-abc/0.1.0/

**Comment by FHTMitchell** [comment]
I'm seeing the same issue in py3.11 now

**Comment by dkmiller** [comment]
Hey everyone - any progress here?

**Comment by zhan9san** [comment]
Hey guys,

Thanks for reporting this issue. I'd like to work on it.

**Comment by barneygale** [comment]
IMO the best way to fix this is to add a dependency on [pathlib-abc](https://pypi.org/project/pathlib-abc/), and make `ArtifactoryPath` inherit from `PathBase`.

**Comment by lukezhangtyler** [comment]
I hope this will be remediated soon.

**Comment by okainov** [comment]
@zhan9san  @beliaev-maksim hi folks, any update on this issue? Given Python 3.12 is fully released and supported, it would be very appreciated that Artifactory library supports it, it's the only item blocking our migration to 3.12 now...

**Comment by allburov** [comment]
We are looking for a volunteer!

**Comment by andrewsiemer** [comment]
+1 this is blocking migrating to python 3.12

**Comment by hacklint** [comment]
Any hope of this being resolved before release of python 3.13?

**Comment by barneygale** [comment]
FWIW I've started a new [**pathlib-artifactory** package](https://pypi.org/project/pathlib-artifactory/) building on the semi-official [**pathlib-abc** package](https://pypi.org/project/pathlib-abc/). It doesn't rely on hacking into the pathlib internals (unlike dohq-artifactory) so it should be on surer footing. But it's missing tons of features and it's certainly not a drop-in replacement for dohq-artifactory yet. Issues and PRs very welcome.

**Comment by mshafer-NI** [comment]
@allburov, @barneygale, I took a swing at using the pathlib-abc, but it's erroring on
```
    from artifactory import ArtifactoryPath
.tox/py39/lib/python3.9/site-packages/artifactory.py:1490: in <module>
    class ArtifactoryPath(pathlib.Path, PureArtifactoryPath):
/pyenv/versions/3.9.18/lib/python3.9/abc.py:106: in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
E   TypeError: multiple bases have instance lay-out conflict
```

You can see my progress here: https://github.com/mshafer-NI/devopshq-artifactory/pull/1

**Comment by LeiYangGH** [comment]
any walkaround?

**Comment by seltsa** [comment]
Any updates for Fedora39 ? Hit the same issue

**Comment by LeiYangGH** [comment]
> FWIW I've started a new [**pathlib-artifactory** package](https://pypi.org/project/pathlib-artifactory/) building on the semi-official [**pathlib-abc** package](https://pypi.org/project/pathlib-abc/). It doesn't rely on hacking into the pathlib internals (unlike dohq-artifactory) so it should be on surer footing. But it's missing tons of features and it's certainly not a drop-in replacement for dohq-artifactory yet. Issues and PRs very welcome.

thanks and could you add a little document on the readme, for example, why create the project, are the usage compatible with devopshq artifactory?

**Comment by FrogWithASock** [comment]
Any updates? Is this project dead? There was no commit to main for 7 months now

**Comment by oscarm3l1n** [comment]
> @barneygale Thank you for your work in core for this. It will be great to simplify the dohq-artifactory codebase.
> 
> Do you suggest any other solution for py312 in the meantime? Should we try subclassing something from py312's `pathlib` prior to `pathlib.PathBase` being available?
> 
> I'm running Python 3.12 on my laptop (Fedora 39), and I've hacked `artifactory.py` so that it doesn't crash. I can list directories and download and upload basic files. My changes are in my [`py312` branch](https://github.com/ktdreyer/artifactory/commits/py312), but I'm not sure they're acceptable for a PR here.

Tested this locally, works like a charm!

**Comment by oscarm3l1n** [comment]
> @barneygale Thank you for your work in core for this. It will be great to simplify the dohq-artifactory codebase.
> 
> Do you suggest any other solution for py312 in the meantime? Should we try subclassing something from py312's `pathlib` prior to `pathlib.PathBase` being available?
> 
> I'm running Python 3.12 on my laptop (Fedora 39), and I've hacked `artifactory.py` so that it doesn't crash. I can list directories and download and upload basic files. My changes are in my [`py312` branch](https://github.com/ktdreyer/artifactory/commits/py312), but I'm not sure they're acceptable for a PR here.

@ktdreyer
Since it's been almost a year. Have you worked around this issue somehow? (sounded on your implementation that it was more of a hack)

**Comment by RoccoMatano** [comment]
I use a little application that depends on `artifactory` and I want to run it with current python versions (i.e. 3.13). I don't know anything about the internals of `artifactory`, but I managed to patch it in such a way, that it fullfills my needs. I have no idea whether this works for all use cases.
For what it's worth, here's the diff:
```
--- C:\prj\progs\py313\Lib\site-packages\artifactory.0.10.1.py	2024-10-08 08:10:50.000000000 +0200
+++ C:\prj\progs\py313\Lib\site-packages\artifactory.py	2024-10-08 08:16:13.000000000 +0200
@@ -419,13 +419,13 @@
         quoted_path = requests.utils.quote(url.partition(parsed_url.host)[2])
         quoted_url = f"{parsed_url.scheme}://{parsed_url.host}{quoted_path}"
 
     return quoted_url
 
 
-class _ArtifactoryFlavour(pathlib._Flavour):
+class _ArtifactoryFlavour:
     """
     Implements Artifactory-specific pure path manipulations.
     I.e. what is 'drive', 'root' and 'path' and how to split full path into
     components.
     See 'pathlib' documentation for explanation how those are used.
 
@@ -437,13 +437,12 @@
     path: relative artifact path within the repository
     """
 
     sep = "/"
     altsep = "/"
     has_drv = True
-    pathmod = pathlib.posixpath
     is_supported = True
 
     def _get_base_url(self, url):
         return get_global_base_url(url)
 
     def compile_pattern(self, pattern):
@@ -1498,25 +1497,33 @@
     """
 
     if sys.version_info.major == 3 and sys.version_info.minor >= 10:
         # see changes in pathlib.Path, slots are no more applied
         # https://github.com/python/cpython/blob/ce121fd8755d4db9511ce4aab39d0577165e118e/Lib/pathlib.py#L952
         _accessor = _artifactory_accessor
+        parser = _ArtifactoryFlavour()
     else:
         # in 3.9 and below Pathlib limits what members can be present in 'Path' class
         __slots__ = ("auth", "verify", "cert", "session", "timeout")
+
+    def __init__(self, *args, **kwargs):
+        # supplying keyword arguments to pathlib.PurePath is deprecated
+        return super().__init__(*args)
 
     def __new__(cls, *args, **kwargs):
         """
         pathlib.Path overrides __new__ in order to create objects
         of different classes based on platform. This magic prevents
         us from adding an 'auth' argument to the constructor.
         So we have to first construct ArtifactoryPath by Pathlib and
         only then add auth information.
         """
         obj = pathlib.Path.__new__(cls, *args, **kwargs)
+        if sys.version_info.major == 3 and sys.version_info.minor >= 12:
+            # supplying keyword arguments to pathlib.PurePath is deprecated
+            obj.__init__(*args)
 
         cfg_entry = get_global_config_entry(obj.drive)
 
         # Auth section
         apikey = kwargs.get("apikey")
         token = kwargs.get("token")
```

**Comment by hacklint** [comment]
> I use a little application that depends on `artifactory` and I want to run it with current python versions (i.e. 3.13). I don't know anything about the internals of `artifactory`, but I managed to patch it in such a way, that it fullfills my needs. I have no idea whether this works for all use cases. For what it's worth, here's the diff:
> 
> ```
> --- C:\prj\progs\py313\Lib\site-packages\artifactory.0.10.1.py	2024-10-08 08:10:50.000000000 +0200
> +++ C:\prj\progs\py313\Lib\site-packages\artifactory.py	2024-10-08 08:16:13.000000000 +0200
> @@ -419,13 +419,13 @@
>          quoted_path = requests.utils.quote(url.partition(parsed_url.host)[2])
>          quoted_url = f"{parsed_url.scheme}://{parsed_url.host}{quoted_path}"
>  
>      return quoted_url
>  
>  
> -class _ArtifactoryFlavour(pathlib._Flavour):
> +class _ArtifactoryFlavour:
>      """
>      Implements Artifactory-specific pure path manipulations.
>      I.e. what is 'drive', 'root' and 'path' and how to split full path into
>      components.
>      See 'pathlib' documentation for explanation how those are used.
>  
> @@ -437,13 +437,12 @@
>      path: relative artifact path within the repository
>      """
>  
>      sep = "/"
>      altsep = "/"
>      has_drv = True
> -    pathmod = pathlib.posixpath
>      is_supported = True
>  
>      def _get_base_url(self, url):
>          return get_global_base_url(url)
>  
>      def compile_pattern(self, pattern):
> @@ -1498,25 +1497,33 @@
>      """
>  
>      if sys.version_info.major == 3 and sys.version_info.minor >= 10:
>          # see changes in pathlib.Path, slots are no more applied
>          # https://github.com/python/cpython/blob/ce121fd8755d4db9511ce4aab39d0577165e118e/Lib/pathlib.py#L952
>          _accessor = _artifactory_accessor
> +        parser = _ArtifactoryFlavour()
>      else:
>          # in 3.9 and below Pathlib limits what members can be present in 'Path' class
>          __slots__ = ("auth", "verify", "cert", "session", "timeout")
> +
> +    def __init__(self, *args, **kwargs):
> +        # supplying keyword arguments to pathlib.PurePath is deprecated
> +        return super().__init__(*args)
>  
>      def __new__(cls, *args, **kwargs):
>          """
>          pathlib.Path overrides __new__ in order to create objects
>          of different classes based on platform. This magic prevents
>          us from adding an 'auth' argument to the constructor.
>          So we have to first construct ArtifactoryPath by Pathlib and
>          only then add auth information.
>          """
>          obj = pathlib.Path.__new__(cls, *args, **kwargs)
> +        if sys.version_info.major == 3 and sys.version_info.minor >= 12:
> +            # supplying keyword arguments to pathlib.PurePath is deprecated
> +            obj.__init__(*args)
>  
>          cfg_entry = get_global_config_entry(obj.drive)
>  
>          # Auth section
>          apikey = kwargs.get("apikey")
>          token = kwargs.get("token")
> ```

Tried this locally, worked fine for what I tested (read-only from Artifactory, no writes tested)

**Comment by LeiYangGH** [comment]
> > I use a little application that depends on `artifactory` and I want to run it with current python versions (i.e. 3.13). I don't know anything about the internals of `artifactory`, but I managed to patch it in such a way, that it fullfills my needs. I have no idea whether this works for all use cases. For what it's worth, here's the diff:
> > ```
> > --- C:\prj\progs\py313\Lib\site-packages\artifactory.0.10.1.py	2024-10-08 08:10:50.000000000 +0200
> > +++ C:\prj\progs\py313\Lib\site-packages\artifactory.py	2024-10-08 08:16:13.000000000 +0200
> > @@ -419,13 +419,13 @@
> >          quoted_path = requests.utils.quote(url.partition(parsed_url.host)[2])
> >          quoted_url = f"{parsed_url.scheme}://{parsed_url.host}{quoted_path}"
> >  
> >      return quoted_url
> >  
> >  
> > -class _ArtifactoryFlavour(pathlib._Flavour):
> > +class _ArtifactoryFlavour:
> >      """
> >      Implements Artifactory-specific pure path manipulations.
> >      I.e. what is 'drive', 'root' and 'path' and how to split full path into
> >      components.
> >      See 'pathlib' documentation for explanation how those are used.
> >  
> > @@ -437,13 +437,12 @@
> >      path: relative artifact path within the repository
> >      """
> >  
> >      sep = "/"
> >      altsep = "/"
> >      has_drv = True
> > -    pathmod = pathlib.posixpath
> >      is_supported = True
> >  
> >      def _get_base_url(self, url):
> >          return get_global_base_url(url)
> >  
> >      def compile_pattern(self, pattern):
> > @@ -1498,25 +1497,33 @@
> >      """
> >  
> >      if sys.version_info.major == 3 and sys.version_info.minor >= 10:
> >          # see changes in pathlib.Path, slots are no more applied
> >          # https://github.com/python/cpython/blob/ce121fd8755d4db9511ce4aab39d0577165e118e/Lib/pathlib.py#L952
> >          _accessor = _artifactory_accessor
> > +        parser = _ArtifactoryFlavour()
> >      else:
> >          # in 3.9 and below Pathlib limits what members can be present in 'Path' class
> >          __slots__ = ("auth", "verify", "cert", "session", "timeout")
> > +
> > +    def __init__(self, *args, **kwargs):
> > +        # supplying keyword arguments to pathlib.PurePath is deprecated
> > +        return super().__init__(*args)
> >  
> >      def __new__(cls, *args, **kwargs):
> >          """
> >          pathlib.Path overrides __new__ in order to create objects
> >          of different classes based on platform. This magic prevents
> >          us from adding an 'auth' argument to the constructor.
> >          So we have to first construct ArtifactoryPath by Pathlib and
> >          only then add auth information.
> >          """
> >          obj = pathlib.Path.__new__(cls, *args, **kwargs)
> > +        if sys.version_info.major == 3 and sys.version_info.minor >= 12:
> > +            # supplying keyword arguments to pathlib.PurePath is deprecated
> > +            obj.__init__(*args)
> >  
> >          cfg_entry = get_global_config_entry(obj.drive)
> >  
> >          # Auth section
> >          apikey = kwargs.get("apikey")
> >          token = kwargs.get("token")
> > ```
> 
> Tried this locally, worked fine for what I tested (read-only from Artifactory, no writes tested)

how to apply this patch after installing the official module?
it would be great if we can copy the patch to our project source folder which then 'monkey patch' the installed official module. is it possible?

**Comment by allburov** [comment]
patching is not the way to go, we should add it as built-in fix (if it works for all cases)

Let's not discuss patching here, I'll mark the comment as **Off Topic** in the future

**Comment by Gris87** [comment]
Hi, any progress with this issue?

**Comment by allburov** [comment]
Hi all participants, we need your help!  :pray: 

Could you test the latest changes in python 3.12 and your script/logic?
It has some backward incompatible changes, but likely most of the usage will not be affected
https://github.com/devopshq/artifactory/pull/463

Here's how you can install it:
```bash
pip install git+https://github.com/auburus/dohq-artifactory@fix/python-312-compat-from-refactor-branch
```

Waiting for your feedback!

**Comment by axel-kah** [comment]
> Could you test the latest changes in python 3.12 and your script/logic? It has some backward incompatible changes, but likely most of the usage will not be affected #463

Tested my script, which uses `ArtifactoryPath`, `RepositoryLocal`, `RepositoryRemote`, with your PR:

- 3.11 ✅ 
- 3.12 ✅ 

Thanks to @auburus for putting in time and energy to help make this lib not a legacy-trap 👍

**Comment by doronz88** [comment]
Does this PR also fix python3.13 support?

**Comment by axel-kah** [comment]
It's a bit tricky to test for my usecases because this package is a transient dependency in many cases but smoke testing with python 3.12 indicates it works just like expected.

Only thing of note was a deprecation warning for 3.14:
```python
  C:\dev\foo\.hatch\foo\Lib\site-packages\artifactory.py:1618: DeprecationWarning: support for supplying keyword arguments to pathlib.PurePath is deprecated and scheduled for removal in Python 3.14
    super().__init__(*args, **kwargs)
```

**Comment by ANVLISTENER** [comment]
Hi Everyone, 

When can we expect this to be tested clearly and be merged. We're literally waiting of this to happen as there are blockers in Ubuntu 24.04 depending on python3.12 completely hardcoded in the OS. 

Once, we merge we would be in relief. 

Please fix and merge it if it fixes the issue ASAP. 

humble request please. 

thank you.

**Comment by johannesloibl** [comment]
> Hi Everyone,
> 
> When can we expect this to be tested clearly and be merged. We're literally waiting of this to happen as there are blockers in Ubuntu 24.04 depending on python3.12 completely hardcoded in the OS.
> 
> Once, we merge we would be in relief.
> 
> Please fix and merge it if it fixes the issue ASAP.
> 
> humble request please.
> 
> thank you.

You could help testing it and give feedback in order to help merging this fix "ASAP" ;)

**Comment by ANVLISTENER** [comment]
I hope we can have a clear support in the future for future releases of python. 

I hope easy way is to restrict a version to support with transient fix and later versions with pure support later( alternate native code as per python 3.13 or later). 

we will need see it in the slightly middle future kind of by mid or later in 2025. it is a blocker in the real time implementations In our use case with artifactory as dependency.

**Comment by ANVLISTENER** [comment]
@johannesloibl I have limited knowledge on this and as per little feedback it works clean for our use case. 

This was the response: 

`I have confirmed that this fix does work for Ubuntu 24.`

**Comment by axel-kah** [comment]
> I hope we can have a clear support in the future for future releases of python.

[...]

> we will need see it in the slightly middle future kind of by mid or later in 2025. it is a blocker in the real time implementations In our use case with artifactory as dependency.

You do realize this is an open source project with no funding [and limited commitment ](https://github.com/devopshq/artifactory/issues/430#issuecomment-2358247968) from the maintainer ?

Don't get me wrong, this is the best artifactory python lib I know of, but if it's that important to you or your business, then treat it as such and invest energy/time/money to keep it healthy or manage your expectations.

**Comment by ANVLISTENER** [comment]
@axel-kah I understand the perspective, but the wish is this to be have a fix and be make it better. 

Shared my thoughts to it's best it should and as I am aware of this is the best artifactory python lib I know of as said.

**Comment by ANVLISTENER** [comment]
@axel-kah It works fine and I did test for this issue is no more.

**Comment by allburov** [comment]
Shouts to @auburus  for the hard work and the fix, so far it's working for all cases, as I can understand.

Let's set a deadline - **21 January 2025**. If no critical bugs found before that date - we'll merge https://github.com/devopshq/artifactory/pull/463 and make a release :rocket:

**Comment by LeiYangGH** [comment]
could anyone explain the steps to test the version to be merged? by clone source to local and install from folder? or pip install some dev version from pypi?

**Comment by allburov** [comment]
Now you can test it from the main repo!
We've merged all changes and waiting for feedback 🙏 
```
pip install git+https://github.com/devopshq/artifactory@master
```

**Comment by LeiYangGH** [comment]
confirm the master branch can work well in my conda python 3.12 env, I mainly tried the aql, upload and download.
artifactory version: Enterprise Plus 7.71.23

**Comment by allburov** [comment]
`dohq-artifactory 1.0.0` is out with Python 3.12 support 🚀 
Thank you all for the work and testing, that was really helpful and inspiring move!

**Comment by jameskhedley** [comment]
Just FYI, I'm still getting a broken package doing just doing `pip install artifactory` on Fedora 42.

Easy to work around if you know how but not ideal.

**Comment by allburov** [comment]
@jameskhedley we use a different package name

https://github.com/devopshq/artifactory?tab=readme-ov-file#install
```bash
pip install dohq-artifactory
```

**Comment by jameskhedley** [comment]
Indeed, had followed a blog I found online without checking the readme. Thanks.
