### ISSUE TITLE
Unable to manage group's users on Artifactory SaaS

### ISSUE THREAD

**Issue by vittoriocanilli** [devopshq/artifactory#431]
I am using Artifactory SaaS and I am trying to create a group with users as specified in the [documentation](https://github.com/devopshq/artifactory/tree/5278d0686671c8dea0401a21c2d40b04d3e0ffb5#internal):

```python
from artifactory import ArtifactorySaaSPath
from dohq_artifactory import Group

artifactory_ = ArtifactorySaaSPath(
                'https://mycompany.jfrog.io/artifactory',
                apikey='myApiKey123'
            )

group = artifactory_.find_group("groupname")

if group is None:
    group = Group(artifactory_, "groupname")
    group.create()

group.read()

group.users = ["admin", "anonymous"]
group.create()
```

The group is created but it has no user as members. I have found this working alternative though:

```python
from artifactory import ArtifactorySaaSPath
from dohq_artifactory import Group

artifactory_ = ArtifactorySaaSPath(
                'https://mycompany.jfrog.io/artifactory',
                apikey='myApiKey123'
            )

group = artifactory_.find_group("groupname")

if group is None:
    group = Group(artifactory_, "groupname")
    group.create()

group.read()

for user in ["admin", "anonymous"]:
  user = artifactory_.find_user(user)
  user.add_to_group(group)
  user.update()
```

But then I have the same problem again if I want to delete all group members:

```python
from artifactory import ArtifactorySaaSPath
from dohq_artifactory import Group

artifactory_ = ArtifactorySaaSPath(
                'https://mycompany.jfrog.io/artifactory',
                apikey='myApiKey123'
            )

group = artifactory_.find_group("groupname")

if group is None:
    group = Group(artifactory_, "groupname")
    group.create()

group.read()

group.users = []
group.update()
```

The previously added users are not removed. I set every time `group.users` as a list, as required by the [source code](https://github.com/devopshq/artifactory/blob/5278d0686671c8dea0401a21c2d40b04d3e0ffb5/dohq_artifactory/admin.py#L471-L472), but that does not seem to work.

Has somebody else had the same issue? I am currently using `dohq-artifactory 0.9.0`. Thanks in advance

**Comment by PatriceG** [comment]
Hi,
We have the same issue.
This is because the _create_json and _read_response method are not using the right attributes for the list of group members.
this should be "userNames".

I'm considering to contribute the fix via a pull request.
However in the meantime, I've fixed it by subclassing the Group class in my app, with GroupFixed.
With  the content below.
I also implemented a method to create a GroupFixed from the Group instance returned by the find method (in order to be able to modify the group members.
This is a quick and dirty hack until the lib is fixed.

`
def create_groupfixed_from_group(group):
                """
                This method creates a GroupFixed object from a Group object.
                This is meant to be a TEMPORARY FIX until the Group class in the lib is fixed.
                """
                groupFixed = GroupFixed(group._artifactory, group.name)
                groupFixed.description = group.description
                groupFixed.auto_join = group.auto_join
                groupFixed.external = group.external
                groupFixed.new_user_default = group.new_user_default
                groupFixed.realm = group.realm
                groupFixed.users = group.users
                return groupFixed

class GroupFixed(Group):
        """
        This is a subclass of Group that fixes the fact that the user members are not set (the wrong json attribute is sent)        
        This should be replaced by a fixed version of Group once the lib is fixed
        """
        def __init__(self, artifactory, name):
                super(GroupFixed, self).__init__(artifactory,name)
                
        
        ##we're overriding the 2 following methods and replacing the usersInGroup attribute by userNames
        def _create_json(self):
                """
                JSON Documentation: https://www.jfrog.com/confluence/display/RTF/Security+Configuration+JSON
                """
                data_json = {
                "name": self.name,
                "description": self.description,
                "autoJoin": self.auto_join,
                "external": self.external,
                "newUserDefault": self.new_user_default,
                "realm": self.realm,
                }

                if isinstance(self.users, list):
                        data_json.update({"userNames": self.users})

                return data_json

        def _read_response(self, response):
                """
                JSON Documentation: https://www.jfrog.com/confluence/display/RTF/Security+Configuration+JSON
                """
                self.name = response.get("name")
                self.description = response.get("description")
                self.auto_join = response.get("autoJoin")
                self.realm = response.get("realm")
                self.realm_attributes = response.get("realmAttributes")
                self.external = response.get("external")
                self.new_user_default = response.get("newUserDefault")
                self.users = response.get("userNames")
`

**Comment by vittoriocanilli** [comment]
@PatriceG Thank you for fixing the issue: it works from version `0.10.2`.

But now I have noticed another small issue when I update the group's members:
```
from artifactory import ArtifactorySaaSPath
from dohq_artifactory import Group

artifactory_ = ArtifactorySaaSPath(
                'https://mycompany.jfrog.io/artifactory',
                apikey='myApiKey123'
            )

group = artifactory_.find_group("groupname")

# here the group is CORRECTLY created with 2 users
if group is None:
    group = Group(artifactory_, "groupname")
    group.users = ["admin", "anonymous"]
    group.create()

# here the group is CORRECTLY updated with 3 users
group.users = ["admin", "anonymous", "user1"]
group.update()

# here the group is NOT updated and it still has 3 users
group.users = []
group.update()

# here the group is CORRECTLY updated with 0 users
group.users = []
group.create()
```

As you can see `group.update()` can add users, but it can not remove them, while `group.create()` can both add and remove users. It is a small issue, but it would be nice to have `group.update()` working correctly as well.

The issue still persists in versions `0.10.3` and `1.0.0`.
